name: a11y-qual-analysis
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - notebook=6.1.*
  - numpy=1.19
  - matplotlib=3.3.*
  - seaborn=0.11.*
  - pandas=1.1.1
  - xlrd=1.2.*
  - jupyter_contrib_nbextensions